### ISSUE TITLE
Add single IP lookup API

### ISSUE THREAD

**Issue by UmanShahzad** [ipinfo/rust#4]
Currently there's a single `lookup` call that accepts a slice of IP strings and returns a hashmap from IP to results, matching the response of the batch API.

This is generally OK in most other languages. But Rust users would probably want something a bit more efficient for the more common use case of a single IP lookup, e.g. per each request they get in their web service. The API is then going to be:

1. more ergonomic for the common use case.
1. more efficient for the common use case.

Add a single IP lookup API which accepts only a single IP and goes the traditional route for making the request, returning a single struct as a response.

**Comment by UmanShahzad** [comment]
This can be a nice first issue for someone learning Rust.

**Comment by UmanShahzad** [comment]
So this is more important to ship than I thought... currently the batch endpoint is only available via a token. We shouldn't be hitting the batch endpoint for single IP lookups.

**Comment by fayzanx** [comment]
Fixed in #30
